"""Footer notes + gate blurbs for kill/promote matrix markdown."""

NOTES = [
    "## Notes",
    "- Smoke budgets (few steps / small pop). Formal claims need longer runs.",
    "- B3/B4/H-SPEC decode on B2 checkpoints; H-SPEC vs B3 on speed+quality.",
    "- Per-hypothesis smoke detail: `docs/results/nano-lm/h*-vs-*.md`.",
    "- Decode trunk H-DEC…H-STACK; formal H-ANN: `formal-hann-vs-kdcos.md`.",
    "- H-SUP/H-INT rows are decode selection scores on teacher, not trained students.",
    "- H-SEL smoke PROMOTE was reversed on formal — see `formal-hsel-vs-b2.md`.",
    "- Agenda: `docs/NANO-STUDENT-AGENDA.md`.",
]

GATES = [
    "H-SPEC gate: tokens/s > B3 and teacher_lp ≥ B3 − 0.05.",
    "H-DEC gate: teacher_lp > B4 (evolved decode knobs).",
    "H-LAT gate: teacher_lp ≥ B4−ε and wall_ms < B4 (latency-aware genes).",
    "H-LAT2 gate: same dual gate as H-LAT with λ≥0.4 and n≤2.",
    "H-DECP gate: teacher_lp > B4 and > GLOBAL (per-prompt bank).",
    "H-DECM gate: teacher_lp > B4 and > H-LAT2 (elite mixture).",
    "H-DECQ gate: teacher_lp > B4 and > H-DECM (quantized codes).",
    "H-DRAFT gate: teacher_lp ≥ B4−ε and wall_ms < B4 (evolved draft knobs).",
    "H-BEAM gate: teacher_lp ≥ B4−ε and wall_ms < B4 (evolved beam search).",
    "H-EARLY gate: teacher_lp ≥ B4−ε and wall_ms < B4 (confidence early-exit).",
    "H-STACK gate: lp ≥ max(H-EARLY,H-DECM)−ε and wall < min tips.",
    "H-HEB gate: not diverged and teacher_lp > B2 (local Hebbian).",
    "H-EPI gate: teacher_lp > B2 (context LR/masks vs fixed LR).",
    "H-LOT gate: teacher_lp > B2; cliff if Δ < −0.5 (lottery ticket).",
    "H-HOP gate: teacher_lp > B2 (Hopfield prior vs AR/KD).",
    "H-BLK gate: lp ≥ B3−ε and wall < B3; crash if Δ < −0.5.",
    "H-DIF gate: lp > B2 and wall ≤ 2×B2 and VRAM ≤ 7 GiB.",
    "H-ADV gate: no mode collapse and teacher_lp > B2 (weak disc).",
    "H-DEB gate: teacher_lp > B2 (dual student; teacher picks).",
    "H-ROUT gate: lp ≥ max(EARLY,DECM)−ε and wall < min tip (conf router).",
    "H-ORAC gate: same dual tip gate (teacher-oracle winner-wall bound).",
    "H-TKD gate: teacher_lp > B2 (top-k sparse KD).",
    "H-REP gate: teacher_lp ≥ B4−ε and wall < B4 (rep-penalty decode).",
    "H-CLIP gate: teacher_lp > B2 (logit-clipped KD).",
    "H-LS gate: teacher_lp > B2 (label-smoothed KD).",
    "H-DECK gate: teacher_lp ≥ H-DEC−ε and wall_save (proxy+top-k search).",
    "H-DECK2 gate: best top_k∈{1,2,3} > H-DECK (k=2) equal pop×gens.",
    "H-PROXY2 gate: teacher_lp > H-DECK @ ≤ teacher_forwards (CE vs self-lp).",
    "H-CASC gate: teacher_lp > B4 and wall_save (proxy→mid→full).",
    "H-BAND gate: teacher_lp > max(H-DECK, H-CASC) (UCB1 arms).",
    "H-DECKL gate: not Pareto-dominated by B4 (DECK+lat claim).",
    "H-POOL gate: teacher_lp > cold H-DECKL (cross-seed warm-start).",
    "H-PARE gate: non-empty front and not Pareto-dominated by B4 (knee claim).",
    "H-LAM gate: stable and teacher_lp > H-BAL.",
    "Selection ops: teacher_lp > H-SEL unless noted (see agenda).",
    "H-HOLD gate: no overfit and teacher_lp > B2 (holdout fit≠eval).",
    "H-LOFI gate: teacher_lp ≥ H-FIT−ε and wall_save.",
    "H-ENT* gate: heads not collapsed and teacher_lp > B2.",
]
