"""Footer notes + gate blurbs for champion matrix markdown."""

GATES = [
    "H-SPEC gate: tokens/s > B3 and teacher_lp ≥ B3 − 0.05.",
    "H-DEC / H-DECK / H-DECKL / H-POOL / H-EARLY: decode tips (see formal docs).",
    "H-CUR / H-CURL / H-CURL2: curriculum train tips (official train = H-CURL2 seq_lo=6).",
    "H-EAR2 gate: lp ≥ EARLY−ε and wall < EARLY (widened early gene).",
    "H-BUD gate: not dominated by EARLY on (lp, wall); quality ≥ EARLY−ε.",
    "H-THIN gate: lp ≥ CURL−ε and wall < CURL on same EARLY decode.",
    "H-Q8 gate: lp ≥ CURL−ε and wall < CURL (INT8 dynamic on same EARLY).",
    "H-EARS gate: lp ≥ EARLY−ε and wall < EARLY (scheduled thr).",
    "H-CURL2 gate: best seq_lo on {4,6,8,10,12} > tip lo=8.",
    "H-COMP gate: lp ≥ EARLY−ε and wall < EARLY (torch.compile).",
    "H-PROX gate: claim lp ≥ POOL−ε (CE-only fit; teacher claim).",
    "H-POOL2 gate: lp ≥ POOL−ε and fit teacher_fwd < POOL (tighter search).",
    "H-CURD gate: teacher_lp > H-CURL2 tip @ equal steps (NLL bins; xor length).",
    "H-STEP gate: claim lp ≥ H-CURL2 tip (early-stop on fit teacher_lp plateau).",
    "H-ALAT gate: teacher_lp > H-CURL2 tip (α/T schedule under CURL stages).",
    "H-FLOP gate: finite mean_tokens_per_s + mean_est_gflops on scored families.",
    "H-EARF gate: lp ≥ EARLY−ε and est_gflops < EARLY (FLOP-aware search).",
    "H-EXIT gate: lp ≥ EARLY−ε and est_gflops < EARLY (min_new↓ + n=1).",
    "H-MID gate: lp ≥ EARLY−ε and est_gflops < EARLY (min_new∈{4,8} + warm-start).",
]

NOTES = [
    "## Notes",
    "- Champion stack only. Purged H-ID history: `docs/results/nano-lm/archive/`.",
    "- H-EAR2 smoke: `docs/results/nano-lm/hear2-vs-hearly.md` (KILL — quality < EARLY−ε).",
    "- H-BUD smoke: `docs/results/nano-lm/hbud-vs-hearly.md` (KILL — quality < EARLY−ε).",
    "- H-THIN: smoke PROMOTE (`hthin-vs-hcurl.md`); formal **KILL** (`formal-hthin-vs-hcurl.md`).",
    "- H-Q8 smoke: `docs/results/nano-lm/hq8-vs-hcurl.md` (KILL — no wall win vs tip).",
    "- H-EARS smoke: `docs/results/nano-lm/hears-vs-hearly.md` (KILL — quality < EARLY−ε).",
    "- H-CURL2: smoke PROMOTE (`hcurl2-vs-hcurl.md`); formal **PROMOTE** lo=6 (`formal-hcurl2-vs-hcurl.md`).",
    "- H-COMP smoke: `docs/results/nano-lm/hcomp-vs-hearly.md` (KILL — no wall win vs EARLY).",
    "- H-PROX smoke: `docs/results/nano-lm/hprox-vs-hpool.md` (KILL — claim quality < POOL−ε).",
    "- H-POOL2 smoke: `docs/results/nano-lm/hpool2-vs-hpool.md` (KILL — quality < POOL−ε).",
    "- H-CURD: smoke PROMOTE (`hcurd-vs-hcurl2.md`); formal **KILL** (`formal-hcurd-vs-hcurl2.md`).",
    "- H-STEP smoke: `docs/results/nano-lm/hstep-vs-hcurl2.md` (KILL — worse lp than tip).",
    "- H-ALAT (αT) smoke: `docs/results/nano-lm/halat-vs-hcurl2.md` (KILL — ≤ tip).",
    "- H-FLOP smoke: `docs/results/nano-lm/hflop-instrumentation.md` (PROMOTE — metrics live).",
    "- H-EARF smoke: `docs/results/nano-lm/hearf-vs-hearly.md` (KILL — no FLOP win vs tip).",
    "- H-EXIT smoke: `docs/results/nano-lm/hexit-vs-hearly.md` (KILL — quality < EARLY−ε; FLOP↓).",
    "- H-MID: smoke PROMOTE (`hmid-vs-hearly.md`); formal **KILL** (`formal-hmid-vs-hearly.md`).",
    "- Smoke budgets are tentative; formal claims need 3 seeds + fit≠eval.",
    "- Agenda: `docs/NANO-STUDENT-AGENDA.md`.",
]
