"""Footer notes for champion matrix markdown."""

GATES = [
    "Tips: H-STAG′ / H-EARLY / H-POOL (TIPD promoted train tip).",
    "Primary recipe: H-PACK (harness/elongated/ood@128/howto/prog/btc; not ood_long).",
    "Deploy: H-DEPL over BUD; QPACK in-harness only; Wave W COMPLETE.",
]

NOTES = [
    "## Notes",
    "- Deploy: `docs/results/nano-lm/RECIPES.md` + DEPL/DOM/PROG/BTC formals.",
    "- Wave W COMPLETE — [wave-w-summary.md](wave-w-summary.md); Wave X ACTIVE (H-TCHR/H-QT/H-GENC PROMOTE; long-L/RAG/CKD/Q*/GENQ/DIST/Q-SLOT/INTERF/ABS-REV/ANNEAL/SPIRAL/GROVER/TUNNEL/BELL/ORACLE1/DNA/DEBATE/HOLO/PHASE/ENTPOS/MEASURE/TELE/WIGNER/CHRONO/MIRROR KILL).",
    "- H-PROG / H-BTC / H-EFF PROMOTE; H-MIXD KILL (runners purged).",
    "- H-TCHR PROMOTE — code teacher wire (`formal-htchr-code-teacher.md`).",
    "- H-QT PROMOTE — int8 weight-only serve (`formal-hqt-quantize.md`).",
    "- H-GENC PROMOTE — genetic serve genome under BUD (`formal-hgenc-genome.md`).",
    "- H-RAG KILL — naive curated prepend (`archive/hrag-retrieve.md`).",
    "- H-CTX KILL — chunked-KV@256 (`archive/hctx-long-window.md`).",
    "- H-CKD KILL — cross-tok soft-KD (`archive/hckd-code-kd.md`).",
    "- H-QCTX KILL — Born-rule attn@256 (`archive/hqctx-born-attn.md`).",
    "- H-QCOMP KILL — shadow KV formal story regress (`archive/hqcomp-shadow-kv.md`).",
    "- H-Q-QUBITKV KILL — critical+sketch KV (`archive/hqubitkv-critical-kv.md`).",
    "- H-GENQ-ABS KILL — amplitude GA → identity (`archive/hgenq-amplitude.md`).",
    "- H-DIST KILL — shared-vocab Neo KD (`archive/hdist-distill.md`).",
    "- H-Q-SLOT KILL — K-slot measure (`archive/hqslot-slots.md`).",
    "- H-Q-INTERF KILL — dual-teacher α-BoN (`archive/hqinterf-interference.md`).",
    "- H-ABS-REV KILL — reverse-prefill (`archive/habsrev-reverse.md`).",
    "- H-Q-ANNEAL KILL — T(t)/conf(t) cooling (`archive/hqanneal-anneal.md`).",
    "- H-ABS-SPIRAL KILL — Hilbert-pos (`archive/habsspiral-spiral.md`).",
    "- H-Q-GROVER KILL — mass amplify (`archive/hqgrover-grover.md`).",
    "- H-Q-TUNNEL KILL — leaky causal identity (`archive/hqtunnel-tunnel.md`).",
    "- H-Q-BELL KILL — distant K/V couple identity (`archive/hqbell-bell.md`).",
    "- H-ABS-ORACLE1 KILL — 1-bit hash vs RAG (`archive/horacle1-oracle.md`).",
    "- H-ABS-DNA KILL — codon 3-mer packs (`archive/hdna-dna.md`).",
    "- H-ABS-DEBATE KILL — dual-half identity (`archive/hdebate-debate.md`).",
    "- H-ABS-HOLO KILL — 4-bit+RFF code↓ (`archive/hholo-holo.md`).",
    "- H-ABS-PHASE KILL — 2D-rotary identity (`archive/hphase-phase.md`).",
    "- H-Q-ENTPOS KILL — pos⊗tok bias identity (`archive/hentpos-entpos.md`).",
    "- H-Q-MEASURE KILL — mid-decode commit code↓ (`archive/hmeasure-measure.md`).",
    "- H-Q-TELE KILL — mid-layer residual teleport identity (`archive/htele-teleport.md`).",
    "- H-Q-WIGNER KILL — signed top-k quasi-prob identity (`archive/hwigner-wigner.md`).",
    "- H-ABS-CHRONO KILL — acausal soft-label shuffle code↓ (`archive/hchrono-chrono.md`).",
    "- H-ABS-MIRROR KILL — anti-teacher margin formal story↓ (`archive/hmirror-mirror.md`).",
    "- H-ABS-CBON KILL — code-teacher BoN commit story↓ (`archive/hcbon-cbon.md`).",
    "- H-ABS-CSAFE KILL — story-floor code BoN low-elig story↓ (`archive/hcsafe-csafe.md`).",
    "- H-ABS-PFB PROMOTE — parent-fallback story-floor BoN (`formal-hpfb-pfb.md`).",
    "- H-ABS-QPFB PROMOTE — PFB on QT-int8 (`formal-hqpfb-qpfb.md`).",
    "- H-ABS-PFB2 PROMOTE — PFB K=2 wall↓ vs k=4 (`formal-hpfb2-pfb2.md`).",
    "- H-ABS-QPFB2 PROMOTE — PFB K=2 on QT-int8 (`formal-hqpfb2-qpfb2.md`).",
    "- H-ABS-BPFB PROMOTE — PFB K=2 on BTC (`formal-hbpfb-bpfb.md`).",
    "- H-ABS-GPFB4 PROMOTE — GENC∘PFB K=4 (`formal-hgpfb4-gpfb4.md`).",
    "- H-ABS-GPFB KILL — GENC∘PFB2 K=2 (`archive/hgpfb-gpfb.md`).",
    "- H-BEAMKV PROMOTE — shared prompt KV across PFB beams (`formal-hbeamkv-beamkv.md`).",
    "- H-TCACHE PROMOTE — teacher LP memo + elig-only code (`formal-htcache-tcache.md`).",
    "- H-SCORERAM PROMOTE — disk/RAM pack score cache (`formal-hscoreram-scoreram.md`).",
    "- H-PFB256 PROMOTE — PFB2 on prog@256 vs EARLY@256 (`formal-hpfb256-pfb256.md`).",
    "- H-ROLL PROMOTE — rolling W+summary; PFB2/segment (`formal-hroll-roll.md`).",
    "- Matrix note: PROG/BTC/MIXD/EFF in wave-w-summary § Kill/promote.",
    "- EvoGen survival archived: `docs/archive/evogen/`.",
    "- Agenda: `docs/NANO-STUDENT-AGENDA.md`.",
]
